# Generated by Django 5.2.1 on 2025-07-02 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_support'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producttracker',
            old_name='product',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='producttracker',
            name='created_at',
        ),
        migrations.AddField(
            model_name='product',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
